[tool.poetry]
name = "back-fitme"
version = "0.1.0"
description = ""
authors = ["Burunoheck <brunoreeck6@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8.10"
Django = "^4.1.1"
djangorestframework = "^3.14.0"
django-cors-headers = "^3.13.0"
djangorestframework-simplejwt = "^5.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
