# Generated by Django 4.1.1 on 2022-09-29 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias', models.PositiveIntegerField()),
                ('gorduras', models.PositiveIntegerField()),
                ('carboidratos', models.PositiveIntegerField()),
                ('proteinas', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_treino', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('video_explicativo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoMuscular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TaxaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_atividade', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_tipo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('senha', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=2)),
                ('data_nasc', models.DateField()),
                ('taxa_metabolica_basal', models.PositiveIntegerField()),
                ('taxa_atividade_idtaxa_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.taxaatividade')),
                ('tipo_usuario_idtipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_reps', models.PositiveIntegerField()),
                ('num_series', models.PositiveIntegerField()),
                ('tempo_descanso', models.TimeField()),
                ('exercicio_idexercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercicio')),
                ('usuario_idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='exercicio',
            name='grupo_muscular_idgrupo_muscular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupomuscular'),
        ),
        migrations.CreateModel(
            name='Alimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias_dia', models.PositiveIntegerField()),
                ('gorduras_dia', models.PositiveIntegerField()),
                ('carboidratos_dia', models.PositiveIntegerField()),
                ('proteinas_dia', models.PositiveIntegerField()),
                ('comida_idcomida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comida')),
                ('usuario_idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
