# Generated by Django 4.1.2 on 2022-12-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="treino",
            name="titulo",
            field=models.CharField(default="Novo Treino", max_length=25),
        ),
        migrations.AlterField(
            model_name="treino",
            name="num_reps",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="treino",
            name="num_series",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="treino",
            name="tempo_descanso",
            field=models.IntegerField(),
        ),
    ]
