# Generated by Django 4.1.2 on 2022-10-26 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="nome",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(default="nome@email.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="senha",
            field=models.CharField(default="senha", max_length=32),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="sexo",
            field=models.CharField(default="MF", max_length=2),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="taxa_atividade_idtaxa_atividade",
            field=models.ForeignKey(
                default="0",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.taxaatividade",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="tipo_usuario_idtipo_usuario",
            field=models.ForeignKey(
                default="0",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tipousuario",
            ),
        ),
    ]
