# Generated by Django 4.1.1 on 2022-10-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='desc_tipo',
            field=models.CharField(max_length=25),
        ),
    ]
