# Generated by Django 4.1.1 on 2022-10-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tipousuario_desc_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='grupomuscular',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
