# Generated by Django 4.1.2 on 2022-12-12 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_treino_titulo_alter_treino_num_reps_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evolucao",
            name="tempo_treino",
        ),
        migrations.RemoveField(
            model_name="treino",
            name="num_reps",
        ),
        migrations.RemoveField(
            model_name="treino",
            name="num_series",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="taxa_atividade",
        ),
        migrations.AlterField(
            model_name="evolucao",
            name="data",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="evolucao",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evolucoes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="exercicio",
            name="descricao",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="exercicio",
            name="grupo_muscular",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercicios",
                to="core.grupomuscular",
            ),
        ),
        migrations.RemoveField(
            model_name="treino",
            name="exercicio",
        ),
        migrations.DeleteModel(
            name="Alimentacao",
        ),
        migrations.DeleteModel(
            name="Comida",
        ),
        migrations.DeleteModel(
            name="TaxaAtividade",
        ),
        migrations.AddField(
            model_name="treino",
            name="exercicio",
            field=models.ManyToManyField(related_name="+", to="core.exercicio"),
        ),
    ]
