# Generated by Django 4.1.2 on 2022-10-26 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_usuario_nome_alter_usuario_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="taxa_atividade_idtaxa_atividade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.taxaatividade"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="tipo_usuario_idtipo_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tipousuario"
            ),
        ),
    ]
