# Generated by Django 4.1.1 on 2022-10-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_exercicio_descricao_alter_grupomuscular_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="evolucao",
            name="massa",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
