# Generated by Django 4.1.2 on 2022-12-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_usuario_taxa_metabolica_basal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evolucao",
            name="taxa_metabolica_basal",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
