# Generated by Django 4.1.1 on 2022-10-26 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_alimentacao_options_alter_comida_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucao',
            name='usuario_idusuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]
