# Generated by Django 4.1.2 on 2022-12-12 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_evolucao_taxa_metabolica_basal"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumSeriesReps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_reps", models.IntegerField()),
                ("num_series", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="treino",
            name="tempo_descanso",
        ),
        migrations.CreateModel(
            name="ExercicioTreino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tempo_descanso", models.IntegerField()),
                (
                    "exercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.exercicio",
                    ),
                ),
                (
                    "num_series_reps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.numseriesreps",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="treino",
            name="exercicio",
            field=models.ManyToManyField(related_name="+", to="core.exerciciotreino"),
        ),
    ]
