# Generated by Django 4.1.4 on 2022-12-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_numseriesreps_remove_treino_tempo_descanso_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exerciciotreino",
            name="num_series_reps",
        ),
        migrations.AddField(
            model_name="exerciciotreino",
            name="num_reps",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exerciciotreino",
            name="num_series",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="exercicio",
            name="nome",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name="NumSeriesReps",
        ),
    ]
