# Generated by Django 4.1.1 on 2022-10-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_evolucao_usuario_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucao',
            name='usuario_idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]
