# Generated by Django 4.1.1 on 2022-10-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_evolucao_usuario_idusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucao',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
