# Generated by Django 4.1.4 on 2022-12-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_exerciciotreino_num_series_reps_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evolucao",
            name="altura",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="evolucao",
            name="imc",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=0, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="evolucao",
            name="massa",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=6, null=True
            ),
        ),
    ]
