# Generated by Django 4.1.4 on 2022-12-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_evolucao_altura_alter_evolucao_imc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evolucao",
            name="altura",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
