# Generated by Django 4.1.1 on 2022-10-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_evolucao_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evolucao',
            name='data',
        ),
    ]
