# Generated by Django 4.1.4 on 2022-12-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_evolucao_altura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evolucao",
            name="massa",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=0, max_digits=4, null=True
            ),
        ),
    ]
