# Generated by Django 4.1.1 on 2022-10-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_evolucao_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucao',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
