# Generated by Django 4.1.1 on 2022-10-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_evolucao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucao',
            name='tempo_treino',
            field=models.DurationField(),
        ),
    ]
