# Generated by Django 4.1.4 on 2022-12-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_rename_exercicio_treino_exercicios_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exerciciotreino",
            name="exercicio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.exercicio",
            ),
        ),
    ]
