# Generated by Django 4.1.1 on 2022-10-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_evolucao_tempo_treino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucao',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='treino',
            name='tempo_descanso',
            field=models.DurationField(),
        ),
    ]
