# Generated by Django 4.1.1 on 2022-10-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_evolucao_data_alter_treino_tempo_descanso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucao',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
